site_name: 开发文档

nav:
  - 首页: index.md
  - 开发技术文档: PALib功能对照手册.md

theme:
  name: material
  features:
    # 🧭 布局相关（核心）
    - navigation.sections      # 左侧导航分组
    - navigation.expand        # 默认展开所有章节
    - navigation.instant       # 页面切换不刷新
    - toc.integrate            # 将右侧目录整合到左侧导航栏
    - content.width            # 正文宽度随屏幕自适应
    - content.code.copy        # 代码块右上角复制按钮
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - table-reader
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - def_list
  - tables

extra_css:
  - styles/extra.css
